name: Erlang rebar CI

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        version: [27, 26, 25, 24, 23, 22, 21]
    container:
      image: erlang:${{ matrix.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: rebar3 compile
    - name: XRef
      run: rebar3 xref
